version: '3.8'

services:
   postgis:
      container_name: postgis
      build:
         context: .
         dockerfile: Dockerfile
      restart: always
      environment:
         POSTGRES_DB: ${POSTGRES_DB:-postgis}
         POSTGRES_USER: ${POSTGRES_USER:-postgres}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      ports:
         - 5432:5432
      networks:
         - postgis
      volumes:
         - ./postgis_data:/var/lib/postgresql/data

   pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      restart: always
      environment:
         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-nsanka@me.com}
         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-changeme}
         PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT:-5050}
      ports:
         - "${PGADMIN_LISTEN_PORT:-5050}:${PGADMIN_LISTEN_PORT:-5050}"
      networks:
         - postgis

networks:
   postgis:
      driver: bridge

volumes:
   postgis_data:
